#include <algorithm>
#include <cassert>
#include <cstdio>
#include <deque>
#include <ios>
#include <iostream>
#include <functional>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <queue>
#include <random>
#include <set>
#include <sstream>
#include <stack>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <vector>
